# Generated by Django 4.2.11 on 2025-05-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Tickets',
        ),
    ]
